name: The input, plus two
defaultToolbox: 
   visible: [ ExpresionCompletar ]
inherit:
  $course: gobstones/curso-lmc
  $assets:
    extra: true
    attires: []
  blocks:
    defaultToolbox: true
  attire: true
  board: true
  execution_speed: true
  source: true
  library: true
  
