name: The Little Man in action
blocks:
  defaultToolbox: |
     <category name="Operaciones básicas">
       <block type="RepeticionCondicional"></block>
       <block type="Asignacion"></block>
       <block type="math_number"></block>
       <block type="List"></block>
     </category>
     <category name="Operaciones de la LMC">
       <block type="PonerLMC_"></block>
       <block type="emptyLMCWithMemSize_"></block>
       <block type="loadInput_OnLMC_"></block>
       <block type="loadProgram_OnLMC_"></block>
       <block type="lmc_isHalted"></block>
       <block type="AnimateLMCProgramOneStepBasedOn_"></block>
       <block type="currentLMCBasedOn_"></block>
     </category>
     <category name="Mis procedimientos" custom="PROCEDURE_CALLS">
     </category>
     <category name="Mis funciones" custom="FUNCTION_CALLS">
     </category>
     <category name="Definiciones">
       <block type="procedures_defnoreturn"></block>
       <block type="DefinicionDeFuncionSimpleConParametrosDeclarativa"></block>
       <block type="DefinicionDeFuncionDeclarativa"></block>
     </category>
execution_speed:
  active: high
  user_permissions:
    can_change_speed: true
inherit:
  $course: gobstones/curso-LMC
  $assets:
    extra: true
    attires: []
  attire: true
  board: true
  source: true
  library: true
  
