name: One input to output
attire:
  active: None
  user_permissions:
    can_toggle_visibility: true
  visible: false
blocks:
  disabled: [ 
            ]
  visible:  [ 
            ]
board:
  active: 1
  initial_board_source: selected
  visible_edition: true
  collapse_toolbox: false
  user_permissions:
    can_view_attire_section: true
    can_edit_board: false
    can_change_initial_board: false
    can_change_initial_board_source: false
    can_view_size_section: false
execution_speed:
  active: instantaneous
  user_permissions:
    can_change_speed: true
source:
  visible: true
  percentage: 0.80  
library:
  visible: false

inherit:
  $course: gobstones/curso-lmc
  $assets:
    extra: true
    attires: []
  blocks:
    defaultToolbox: true
  board: true
  execution_speed: true
  source: true
  library: true
  
