name: One input to output
attire:
  active: None
  user_permissions:
    can_toggle_visibility: true
  visible: false
blocks:
  disabled: [ 
            ]
  visible:  [ ExpresionCompletar
            ]

inherit:
  $course: gobstones/curso-lmc
  $assets:
    extra: true
    attires: []
  blocks:
    defaultToolbox: true
  board: true
  execution_speed: true
  source: true
  library: true
  
